events {
    worker_connections 1024;
}

http {
    upstream pawspective {
        server pawspective:8080;
    }

    server {
        listen 80;
        listen [::]:80;
        server_name pawspective.ru www.pawspective.ru;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
            access_log off;
            log_not_found off;
            default_type "text/plain";
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name pawspective.ru www.pawspective.ru;

        ssl_certificate     /etc/nginx/certs/live/pawspective.ru/fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/live/pawspective.ru/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        add_header X-Frame-Options DENY;
        add_header X-Content-Type-Options nosniff;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
            access_log off;
            log_not_found off;
            default_type "text/plain";
        }

        location / {
            proxy_pass http://pawspective;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_connect_timeout 5s;
            proxy_read_timeout 60s;
        }
    }
}
