components_manager:
    task_processors:

        main-task-processor:
            worker_threads: $worker-threads

        fs-task-processor:
            worker_threads: $worker-fs-threads

    default_task_processor: main-task-processor

    components:
        testsuite-support:

        http-client:

        http-client-middleware-pipeline:

        default-secdist-provider:
            config: /home/user/pawspective/secdist.json
            missing-ok: false


        secdist:
            provider: default-secdist-provider
        

        dns-client:
            fs-task-processor: fs-task-processor
            
        postgres-db:
            dbconnection: 'postgresql://user:password@localhost:5432/postgres-db'
            blocking_task_processor: fs-task-processor
            dns_resolver: async

        jwt-service:
            secret_key: $JWT_SECRET_KEY
            access_ttl: 3600
            refresh_ttl: 86400
        
        session-service-pg:
            load-enabled: true 
        
        organization-repository:
            load-enabled: true

        city-repository:
            load-enabled: true

        city-service:
            load-enabled: true

        organization-service:
            load-enabled: true

        user-repository: 
            load-enabled: true

        user-service:
            load-enabled: true

        animal-repository: 
            load-enabled: true

        breed-repository: 
            load-enabled: true

        animal-service:
            load-enabled: true

        breed-service:
            load-enabled: true

        server:
            listener:
                port: $server-port
                task_processor: main-task-processor

        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: $logger-level
                    overflow_behavior: discard

        handler-health-check:
            path: /health
            method: GET
            task_processor: main-task-processor

        handler-auth-me:
            path: /auth/me
            method: GET
            task_processor: main-task-processor
            auth:
                types:
                    - jwt
                required: true
        
        handler-auth-refresh:
            path: /auth/refresh
            method: POST
            task_processor: main-task-processor

        handler-user-registration:
            path: /user/register
            method: POST
            task_processor: main-task-processor
        
        handler-auth-login:
            path: /auth/login
            method: POST
            task_processor: main-task-processor

        handler-user-update:
            path: /user/{id}
            method: PUT
            task_processor: main-task-processor
            auth:
                types:
                    - jwt
                required: true

        handler-auth-logout:
            path: /auth/logout
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                    - jwt
                required: true

        handler-city-list:
            path: /city
            method: GET
            task_processor: main-task-processor

        handler-org-registration:
            path: /orgs
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                    - jwt
                required: true

        handler-org-update:
            path: /orgs/{id}
            method: PUT
            task_processor: main-task-processor
            auth:
                types:
                    - jwt
                required: true

        handler-organization-get:
            path: /orgs/{id}
            method: GET
            task_processor: main-task-processor
