components_manager:
    task_processors:

        main-task-processor:
            worker_threads: $worker-threads

        fs-task-processor:
            worker_threads: $worker-fs-threads

    default_task_processor: main-task-processor

    components:
        testsuite-support:
            testsuite-tasks-enabled: true

        tests-control:
            load-enabled: $is-testing
            path: /tests/{action}
            method: POST
            task_processor: main-task-processor

        http-client:

        http-client-middleware-pipeline:

        default-secdist-provider:
            config: $secdist-path
            missing-ok: false


        secdist:
            provider: default-secdist-provider
        

        dns-client:
            fs-task-processor: fs-task-processor
            
        postgres-db:
            dbalias: postgres-db
            blocking_task_processor: fs-task-processor
            dns_resolver: async

        jwt-service:
            secret_key: $JWT_SECRET_KEY
            access_ttl: 3600
            refresh_ttl: 86400

        s3-service:
            timeout: 5000
        
        session-service-pg:
            load-enabled: true 
        
        organization-repository:
            load-enabled: true

        city-repository:
            load-enabled: true

        city-service:
            load-enabled: true

        organization-service:
            load-enabled: true

        user-repository: 
            load-enabled: true

        user-service:
            load-enabled: true

        animal-repository:
            load-enabled: true

        adopt-request-repository:
            load-enabled: true

        adopt-request-service:
            load-enabled: true

        breed-repository: 
            load-enabled: true

        animal-service:
            load-enabled: true

        breed-service:
            load-enabled: true

        post-repository:
            load-enabled: true

        post-service:
            load-enabled: true

        review-repository:
            load-enabled: true

        review-service:
            load-enabled: true

        session-cleaner:
            load-enabled: true
            cluster: postgres-db
            table: service_distlocks
            lock-ttl: 60s
            pg-timeout: 10s
            restart-delay: 30s
            autostart: true
            lockname: session-cleaner-lock
            task-processor: main-task-processor
            testsuite-support: true


        server:
            listener:
                port: $server-port
                task_processor: main-task-processor

        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: $logger-level
                    overflow_behavior: discard

        handler-health-check:
            path: /health
            method: GET
            task_processor: main-task-processor

        handler-auth-me:
            path: /auth/me
            method: GET
            task_processor: main-task-processor
            auth:
                types:
                    - jwt
                required: true
        
        handler-auth-refresh:
            path: /auth/refresh
            method: POST
            task_processor: main-task-processor

        handler-user-registration:
            path: /user/register
            method: POST
            task_processor: main-task-processor
        
        handler-auth-login:
            path: /auth/login
            method: POST
            task_processor: main-task-processor

        handler-user-update:
            path: /user/{id}
            method: PUT
            task_processor: main-task-processor
            auth:
                types:
                    - jwt
                required: true

        handler-auth-logout:
            path: /auth/logout
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                    - jwt
                required: true

        handler-user-delete:
            path: /user/{id}
            method: DELETE
            task_processor: main-task-processor
            auth:
                types:
                    - jwt
                required: true

        handler-city-list:
            path: /city
            method: GET
            task_processor: main-task-processor

        handler-breed-list:
            path: /breeds
            method: GET
            task_processor: main-task-processor

        handler-org-registration:
            path: /orgs
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                    - jwt
                required: true

        handler-org-update:
            path: /orgs/{id}
            method: PUT
            task_processor: main-task-processor
            auth:
                types:
                    - jwt
                required: true

        handler-org-search:
            path: /orgs
            method: GET
            task_processor: main-task-processor

        handler-organization-get:
            path: /orgs/{id}
            method: GET
            task_processor: main-task-processor

        handler-org-delete:
            path: /orgs/{id}
            method: DELETE
            task_processor: main-task-processor
            auth:
                types:
                    - jwt
                required: true

        handler-animal-registration:
            path: /animals
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                    - jwt
                required: true

        handler-animal-update:
            path: /animals/{id}
            method: PUT
            task_processor: main-task-processor
            auth:
                types:
                    - jwt
                required: true

        handler-organization-animals:
            path: /orgs/{id}/animals
            method: GET
            task_processor: main-task-processor
            auth:
                types:
                    - jwt
                required: false

        handler-animal-list:
            path: /animals
            method: GET
            task_processor: main-task-processor
            auth:
                types:
                    - jwt
                required: false

        handler-me-adopted-animals-pending-review:
            path: /me/adopted-animals/pending-review
            method: GET
            task_processor: main-task-processor
            auth:
                types:
                    - jwt
                required: true

        handler-animal-filters:
            path: /animals/filters
            method: GET
            task_processor: main-task-processor

        handler-animal-get:
            path: /animals/{id}
            method: GET
            task_processor: main-task-processor
            auth:
                types:
                    - jwt
                required: false

        handler-animal-delete:
            path: /animals/{id}
            method: DELETE
            task_processor: main-task-processor
            auth:
                types:
                    - jwt
                required: true

        handler-posts-get:
            path: /posts
            method: GET
            task_processor: main-task-processor
            
        handler-post-create:
            path: /posts
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                    - jwt
                required: true

        handler-review-create:
            path: /reviews
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                    - jwt
                required: true

        handler-review-update:
            path: /reviews/{id}
            method: PUT
            task_processor: main-task-processor
            auth:
                types:
                    - jwt
                required: true

        handler-review-get:
            path: /reviews
            method: GET
            task_processor: main-task-processor
            auth:
                types:
                    - jwt
                required: false

        handler-review-delete:
            path: /reviews/{id}
            method: DELETE
            task_processor: main-task-processor
            auth:
                types:
                    - jwt
                required: true

        handler-post-update:
            path: /posts/{id}
            method: PUT
            task_processor: main-task-processor
            auth:
                types:
                    - jwt
                required: true

        handler-post-delete:
            path: /posts/{id}
            method: DELETE
            task_processor: main-task-processor
            auth:
                types:
                    - jwt
                required: true

        handler-requests-get:
            path: /requests
            method: GET
            task_processor: main-task-processor
            auth:
                types:
                    - jwt
                required: true

        handler-request-accept:
            path: /requests/accept/{id}
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                    - jwt
                required: true

        handler-request-deny:
            path: /requests/deny/{id}
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                    - jwt
                required: true

        handler-animal-adopt:
            path: /animals/{id}/adopt
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                    - jwt
                required: true

        handler-upload-photo:
            path: /upload/photo
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                    - jwt
                required: true
